### ISSUE TITLE
cmg_sdd function is not available

### ISSUE THREAD

**Issue by DataEnthusiastSathya** [yqueau/normal_integration#4]
Hi @yqueau ,
Thanks for your paper and code.
While executing the code, I get an error, function "cmg_sdd" is not found.

**Comment by yqueau** [comment]
Hi, 

Thank you for your interest in our research. This error may appear if the CMG library is not installed. It can be downloaded here: http://www.cs.cmu.edu/~jkoutis/cmg.html

If CMG it is not installed, set the "precond" parameter to "none" (no preconditioning, can be very slow for large data) or to "ichol" (modified incomplete Cholesky preconditioner advised in [6], slower than CMG but overall OK). This will be slower, but it should run without any additional library.

Hope this helps, 
Yvain
