### ISSUE TITLE
Help with rescaling

### ISSUE THREAD

**Issue by DataEnthusiastSathya** [yqueau/normal_integration#5]
Hi @yqueau ..thanks for your amazing support. I have normal files like the below one from DILIGENT data set. Kindly let me know the rescaling I should be doing.

Normal_gt

https://sites.google.com/site/photometricstereodata/
![Normal_gt](https://user-images.githubusercontent.com/34202316/59718301-8abcdb00-9237-11e9-9de0-567a7cd90246.png)

**Comment by yqueau** [comment]
Hi, 

The following script will integrate your normal image using orthographic projection. 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear
close all

% Load the integration functions from the git repo
addpath(genpath('normal_integration/'));

% Load normal map, and convert it to my 3D-space coordinates
N = double(imread('59718301-8abcdb00-9237-11e9-9de0-567a7cd90246.png')); 
Nx = -(N(:,:,2)/128-1);
Ny = N(:,:,1)/128-1;
Nz = (N(:,:,3)/128-1);

% Get (p,q) from normals
p = -Nx./Nz;
q = -Ny./Nz;

% In case some normal are weird (not pointing towards camera => do harmonic depth completion in that case by setting (p,q) = 0)
p(Nz<0.01) = 0;
q(Nz<0.01) = 0;

% Get mask from the normals (a bit hacky, better do the mask manually with Gimp...)
mask = (Nx~=1) & (Ny~=-1) & (Nz~=-1); 

% Set parameters for integration
lambda = 1e-6*ones(size(p)); % Uniform field of weights (nrows x ncols)
z0 = zeros(size(p)); % Null depth prior (nrows x ncols)
solver = 'pcg'; % Solver ('pcg' means conjugate gradient, 'direct' means backslash i.e. sparse Cholesky) 
precond = 'ichol'; % Preconditioner ('none' means no preconditioning, 'ichol' means incomplete Cholesky, 'CMG' means conjugate combinatorial multigrid -- the latter is fastest, but it need being installed, see README)

% Run integration
z = smooth_integration(p,q,mask,lambda,z0,solver,precond);

% Display result
figure
surfl(z,[-135 30]);
view(-35,20)
axis ij;
shading flat;
colormap gray;
axis equal;
grid off
axis off
title('Reconstruction with mask','Interpreter','Latex','Fontsize',14)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by DataEnthusiastSathya** [comment]
Amazing. Thanks a lot @yqueau..it works.. can you help me with understanding the logic behind this or any link that I can refer to

**Comment by yqueau** [comment]
Sure. You can see for instance:
- Sect. 2.1 in https://hal.archives-ouvertes.fr/hal-02118484 , which tells you about the link between surface normals and depth gradient i.e., how to construct (p,q). 
- Sect .3 in https://hal.archives-ouvertes.fr/hal-02118476, which explains the integration routine 'smooth_integration'.
The rest of the code is straightforward I think. 

Best,
Yvain

**Comment by DataEnthusiastSathya** [comment]
Thanks again...your support is fantabulous

**Comment by yqueau** [comment]
My pleasure :)
